"""``TFoam`` as ``RooFoamGenerator`` drives it: RooFit's default event generator.

A pdf with no generator of its own - most of them - is generated by RooFit
with ROOT's FOAM (S. Jadach, Comput. Phys. Commun. 152 (2003) 55). FOAM first
builds a foam: it splits the unit hypercube into cells, one cut at a time,
always cutting the cell whose short Monte Carlo exploration says it is the
worst fit to the density, until it has as many cells as it was asked for.
Then an event is a cell chosen in proportion to its share of the total, a
uniform point inside it, and a rejection against the density there.

Every choice in that process - which cell to cut, along which edge, where -
is made from random numbers, so a foam built from different numbers, or the
same numbers taken in a different order, is a different foam and gives
different events. To give ROOT's events, this is ``TFoam`` line for line: the
same draws from the same ``TRandom3`` in the same order, the same
comparisons, the same floating-point expressions in the same order, so the
cells are ROOT's cells and the events ROOT's events. Two things are made
faster without changing a number: the draws of an exploration that cannot
end early are taken as one array (``RndmArray`` of ``TRandom3`` gives the
successive ``Rndm()`` values), and running sums use ``cumsum``, which adds in
order, never NumPy's pairwise ``sum``.

Left out, because they touch neither the random numbers nor the events: the
weight histogram and ``TFoamMaxwt`` monitor, the debug histograms, the chat
output, and the predefined and inhibited divisions RooFit never sets. Where
ROOT only prints an error and carries on into undefined behaviour - a density
with no positive value, a cell with no edge to cut - this refuses instead.

:class:`FoamGenerator` is ``RooFoamGenerator``: the foam over the ranges of
the observables, with RooFit's settings for its dimension.
"""

from __future__ import annotations

import heapq
import math
from collections.abc import Callable
from typing import Any

import numpy as np

from xrdroot.random import TRandom3

from .foamcells import Cell

__all__ = ["Foam", "FoamGenerator", "ROOFIT_CELLS"]

#: ``gHigh`` and ``gVlow`` in ``TFoam.cxx``: the starting minimum and maximum.
HIGH = 1.0e150
VLOW = -1.0e150
#: ``RooFoamGenerator``'s ``nCell1D``, ``nCell2D``, ``nCell3D``: cells by dimension.
ROOFIT_CELLS = {1: 30, 2: 500, 3: 5000}
#: ``nCellND``: the cells for four dimensions or more.
ROOFIT_CELLS_ND = 10000
#: ``nSample``: RooFit's (and ``TFoam``'s) draws for exploring each cell.
ROOFIT_SAMPLES = 200

#: A density over the unit hypercube: points ``(n, dim)`` in, ``n`` values out.
Density = Callable[[Any], Any]


class Foam:
    """``TFoam``: a foam of cells over the unit hypercube, and events drawn from it.

    ``density`` takes an array of points, shape ``(n, dim)``, in the unit
    hypercube and returns their ``n`` values. Only ratios of values decide
    anything, so the density need not be normalised; but for ROOT's events
    to the last bit it must be the numbers ROOT's integrand returns, since a
    rescaled density rounds differently. The keyword options are ``TFoam``'s
    setters, with ``TFoam``'s defaults: ``n_cells`` (``SetnCells``),
    ``n_sampl`` (``SetnSampl``), ``n_bin`` (``SetnBin``), ``ev_per_bin``
    (``SetEvPerBin``), ``opt_drive`` (1 to reduce the variance, 2 the maximum
    weight), ``opt_rej`` (1 for unweighted events) and ``max_wt_rej``.

    :meth:`initialize` builds the foam and :meth:`make_event` then makes one
    event, left in :attr:`mc_vect` with its weight in :attr:`mc_wt`.
    """

    def __init__(
        self, density: Density, dim: int, rng: Any, *, n_cells: int = 1000,
        n_sampl: int = 200, n_bin: int = 8, ev_per_bin: int = 25,
        opt_drive: int = 2, opt_rej: int = 1, max_wt_rej: float = 1.1,
    ) -> None:
        _check_options(dim, n_sampl, n_bin, opt_drive)
        self.density = density
        self.dim = dim
        self.rng = rng
        self.n_cells = n_cells
        self.n_sampl = n_sampl
        self.n_bin = n_bin
        self.ev_per_bin = ev_per_bin
        self.opt_drive = opt_drive
        self.opt_rej = opt_rej
        self.max_wt_rej = max_wt_rej
        self.cells: list[Cell] = []
        self._drivers: list[tuple[float, int]] = []
        self.active: list[Cell] = []
        self.prim_acu: list[float] = []
        self.prime = 0.0
        self.n_calls = 0
        self.mc_vect: Any = np.zeros(dim)
        self.mc_wt = 0.0
        self._reset_sums()

    def _reset_sums(self) -> None:
        """Zero the sums of the generation's weights, as ``Initialize`` ends by doing."""
        self.sum_wt = 0.0
        self.sum_wt2 = 0.0
        self.sum_ove = 0.0
        self.nev_gen = 0.0
        self.wt_max = VLOW
        self.wt_min = HIGH

    # -- the build-up -------------------------------------------------------------------

    def initialize(self) -> None:
        """``Initialize``: explore the root cell, grow the foam, and list the active cells."""
        root = Cell(None, 0)
        self.cells = [root]
        self._drivers = []
        self._explore(root)
        self._grow()
        self._make_active_list()
        self._reset_sums()

    def _grow(self) -> None:
        """``Grow``: cut the cell with the largest driver integral until the cells run out.

        ``PeekMax`` looks through every cell each time; an active cell's
        driver integral never changes once it is explored, so a heap keyed on
        its size and then its place in the list picks the same cell - the
        first of the largest - without the search. A NaN is never the
        largest, and never enters the heap.
        """
        while len(self.cells) + 1 < self.n_cells:
            if not self._drivers:
                raise ValueError(
                    "No cell of the foam has a driver integral to choose it by; "
                    "the density must be finite."
                )
            self._divide(self.cells[heapq.heappop(self._drivers)[1]])

    def _offer(self, cell: Cell) -> None:
        """Put an explored active cell among those ``PeekMax`` may choose."""
        if not math.isnan(cell.driv):
            heapq.heappush(self._drivers, (-abs(cell.driv), cell.serial))

    def _divide(self, cell: Cell) -> None:
        """``Divide``: retire the cell and explore its two daughters, first then second."""
        if not 0 <= cell.best < self.dim:
            raise ValueError(
                "A cell of the foam has no edge to cut along, which happens only "
                "when the density is negative; FOAM needs a density of at least zero."
            )
        cell.active = False
        cell.dau0 = Cell(cell, len(self.cells))
        cell.dau1 = Cell(cell, len(self.cells) + 1)
        self.cells += [cell.dau0, cell.dau1]
        self._explore(cell.dau0)
        self._explore(cell.dau1)

    def _make_active_list(self) -> None:
        """``MakeActiveList``: the active cells and their cumulative share of the primary."""
        self.active = [cell for cell in self.cells if cell.active]
        prime = 0.0
        for cell in self.active:
            prime += cell.prim
        if prime == 0.0:
            raise ValueError(
                "The density is zero everywhere FOAM looked, so there is nothing "
                "to generate from."
            )
        self.prime = prime
        total = 0.0
        self.prim_acu = []
        for cell in self.active:
            total = total + cell.prim / prime
            self.prim_acu.append(total)

    # -- exploring a cell ---------------------------------------------------------------

    def _explore(self, cell: Cell) -> None:
        """``Explore``: sample the cell, choose its cut, set its and its ancestors' integrals."""
        cell.place(self.dim)
        int_old, dri_old = cell.intg, cell.driv
        alpha, wt, sums = self._sample(cell)
        nev_mc = float(len(wt))
        int_true = sums[0] / (nev_mc + 0.000001)
        content = _edge_histogram(alpha, wt, self.n_bin)
        if self.opt_drive == 1:
            sumw2 = _edge_histogram(alpha, wt * wt, self.n_bin)
            cell.best, cell.xdiv = _varedu(sums, nev_mc, content, sumw2)
            int_prim = math.sqrt(sums[1] / nev_mc)
            int_driv = int_prim - int_true
        else:
            cell.best, cell.xdiv = _carver(content)
            int_prim = float(np.fmax.reduce(wt, initial=VLOW))
            int_driv = int_prim - int_true
        cell.intg, cell.driv, cell.prim = int_true, int_driv, int_prim
        parent = cell.parent
        while parent is not None:
            parent.intg = parent.intg + int_true - int_old
            parent.driv = parent.driv + int_driv - dri_old
            parent = parent.parent
        self._offer(cell)

    def _sample(self, cell: Cell) -> tuple[Any, Any, list[float]]:
        """The exploration's points (as fractions of the cell), their weights, and their sums.

        ``Explore`` stops early once the effective number of events reaches
        ``n_bin * ev_per_bin``. That cannot happen before that many points
        have been drawn, so those are drawn at once; from there on it is one
        point at a time, as ROOT goes, so that no draw is taken that ROOT
        would have left for the next cell.
        """
        threshold = self.n_bin * self.ev_per_bin
        first = min(self.n_sampl, max(threshold - 1, 1))
        alpha, wt = self._weights(cell, first)
        sums = [float(np.cumsum(wt)[-1]), float(np.cumsum(wt * wt)[-1])]
        alphas, wts = [alpha], [wt]
        for _ in range(first, self.n_sampl):
            if _nev_eff(sums) >= threshold:
                break
            alpha, wt = self._weights(cell, 1)
            one = float(wt[0])
            sums[0] += one
            sums[1] += one * one
            alphas.append(alpha)
            wts.append(wt)
        self.n_calls += sum(len(w) for w in wts)
        return np.concatenate(alphas), np.concatenate(wts), sums

    def _weights(self, cell: Cell, count: int) -> tuple[Any, Any]:
        """``count`` uniform points in the cell and their weights, ``volume * density``."""
        alpha = np.asarray(self.rng.rndm(count * self.dim)).reshape(count, self.dim)
        points = cell.posi + alpha * cell.size
        values = np.asarray(self.density(points), dtype=np.float64).reshape(count)
        return alpha, cell.volume * values

    # -- generation ---------------------------------------------------------------------

    def make_event(self) -> Any:
        """``MakeEvent``: the next event, kept in :attr:`mc_vect`, its weight in :attr:`mc_wt`."""
        while True:
            cell = self._gener_cel2()
            alpha = np.asarray(self.rng.rndm(self.dim))
            vect = cell.posi + alpha * cell.size
            value = float(np.asarray(self.density(vect.reshape(1, self.dim))).reshape(1)[0])
            mcwt = cell.volume * value / cell.prim
            self._count(vect, mcwt)
            if self.opt_rej != 1 or self._accept(mcwt):
                return self.mc_vect.copy()

    def _count(self, vect: Any, mcwt: float) -> None:
        """Keep the event and add its weight to the sums, as ``MakeEvent`` does before rejecting."""
        self.mc_vect = vect
        self.mc_wt = mcwt
        self.n_calls += 1
        self.sum_wt += mcwt
        self.sum_wt2 += mcwt * mcwt
        self.nev_gen += 1
        self.wt_max = max(self.wt_max, mcwt)
        self.wt_min = min(self.wt_min, mcwt)

    def _accept(self, mcwt: float) -> bool:
        """The rejection that makes events of weight one, drawing one number."""
        if self.max_wt_rej * self.rng.rndm() > mcwt:
            return False
        if mcwt < self.max_wt_rej:
            self.mc_wt = 1.0
        else:
            self.mc_wt = mcwt / self.max_wt_rej
            self.sum_ove += self.mc_wt - self.max_wt_rej
        return True

    def _gener_cel2(self) -> Cell:
        """``GenerCel2``: an active cell by its share of the primary, by interpolation search."""
        acu = self.prim_acu
        random = self.rng.rndm()
        lo, hi = 0, len(acu) - 1
        flo, fhi = acu[lo], acu[hi]
        while lo + 1 < hi:
            hit = lo + int((hi - lo) * (random - flo) / (fhi - flo) + 0.5)
            hit = min(max(hit, lo + 1), hi - 1)
            if acu[hit] > random:
                hi, fhi = hit, acu[hit]
            else:
                lo, flo = hit, acu[hit]
        return self.active[lo] if acu[lo] > random else self.active[hi]


def _check_options(dim: int, n_sampl: int, n_bin: int, opt_drive: int) -> None:
    """Refuse the settings ``TFoam`` cannot build a foam with."""
    if dim < 1:
        raise ValueError(f"FOAM needs at least one dimension, not {dim}.")
    if n_sampl < 1 or n_bin < 1:
        raise ValueError(
            "FOAM needs at least one exploration point and one histogram bin per cell, "
            f"not {n_sampl} and {n_bin}."
        )
    if opt_drive not in (1, 2):
        raise ValueError(
            f"FOAM's driver is 1 (reduce the variance) or 2 (reduce the maximum weight), "
            f"not {opt_drive}."
        )


def _nev_eff(sums: list[float]) -> float:
    """The effective number of events of an exploration so far, ``(sum w)**2 / sum w**2``."""
    return 0.0 if sums[1] == 0.0 else sums[0] * sums[0] / sums[1]


def _edge_histogram(alpha: Any, weights: Any, n_bin: int) -> Any:
    """``fHistEdg``: for each edge, the weights binned by where along it the points fell.

    Row ``k`` is edge ``k``'s ``TH1D`` over [0, 1] with ``n_bin`` bins,
    filled point by point as ``Explore`` fills it. ``bincount`` adds each
    weight to its bin in the order of the points, starting from zero, which
    is the order and the arithmetic of the ``Fill`` calls.
    """
    dim = alpha.shape[1]
    bins = (n_bin * alpha).astype(np.int64) + np.arange(dim) * n_bin
    spread = np.repeat(weights, dim)
    return np.bincount(bins.ravel(), weights=spread, minlength=dim * n_bin).reshape(dim, n_bin)


def _carver(content: Any) -> tuple[int, float]:
    """``Carver``: the edge and cut that carve away the most of the maximum weight.

    For each edge, the carve is how far the bins fall below the highest one;
    the edge with the largest total is cut at the lower end of its deepest
    valley (or its upper end, when the valley starts at the edge). An edge
    whose every bin is negative stops the search where it is, as in ROOT.
    """
    k_best, x_best = -1, 0.5
    carv_max = VLOW
    n_bin = content.shape[1]
    for k, row in enumerate(content):
        bins = [float(b) for b in row]
        bin_max, carv_tot = _carve_total(bins)
        if bin_max < 0:
            return k_best, x_best
        if carv_tot > carv_max:
            carv_max = carv_tot
            j_low, j_up = _deepest_valley(bins, bin_max)
            k_best = k
            x_best = j_low / n_bin if j_low != 0 else (j_up + 1) / n_bin
    return k_best, x_best


def _carve_total(bins: list[float]) -> tuple[float, float]:
    """The highest bin (``TMath::Max`` from ``gVlow``) and how far all bins fall below it."""
    bin_max = VLOW
    for b in bins:
        bin_max = bin_max if bin_max >= b else b
    carv_tot = 0.0
    for b in bins:
        carv_tot = carv_tot + (bin_max - b)
    return bin_max, carv_tot


def _deepest_valley(bins: list[float], bin_max: float) -> tuple[int, int]:
    """The first and last bin of the run carving most below ``bin_max``, first found first."""
    j_low, j_up = 0, len(bins) - 1
    carv_one = VLOW
    for i, the_bin in enumerate(bins):
        i_low = _walk(bins, the_bin, range(i, -1, -1))
        i_up = _walk(bins, the_bin, range(i, len(bins)))
        carve = (i_up - i_low + 1) * (bin_max - the_bin)
        if carve > carv_one:
            carv_one, j_low, j_up = carve, i_low, i_up
    return j_low, j_up


def _walk(bins: list[float], level: float, steps: range) -> int:
    """How far from its start ``steps`` goes before reaching a bin above ``level``."""
    reached = steps[0]
    for j in steps:
        if level < bins[j]:
            break
        reached = j
    return reached


def _varedu(sums: list[float], nent: float, content: Any, sumw2: Any) -> tuple[int, float]:
    """``Varedu``: the edge and cut that most reduce the spread of the weights.

    For each edge, every run of bins is tried as the inside of a cut; the
    edge whose best run gains most over the uncut cell wins, cut at the
    run's lower end (or upper end, when the run starts at the edge). Its
    arithmetic is ROOT's, square roots of NaN and all, so it is done in
    NumPy scalars with their warnings off.
    """
    k_best, x_best = -1, 0.5
    max_gain = 0.0
    n_bin = content.shape[1]
    with np.errstate(all="ignore"):
        ssw = np.sqrt(np.float64(sums[1])) / np.sqrt(np.float64(nent))
        for k in range(content.shape[0]):
            errors = [float(e) ** 2 for e in np.sqrt(sumw2[k])]
            best, x_min, x_max = _best_run(sums[1], nent, list(content[k]), errors)
            gain = ssw - best if best < HIGH else 0.0
            if gain >= max_gain:
                max_gain, k_best = gain, k
                x_best = x_max if int(n_bin * x_min) == 0 else x_min
    return k_best, float(x_best)


def _best_run(
    ssw_all: float, nent: float, content: list[Any], errors: list[float],
) -> tuple[Any, float, float]:
    """The smallest spread over the runs of bins ``[lo, up]``, and the run, first found first."""
    n_bin = len(content)
    best: Any = HIGH
    x_min = x_max = 0.0
    for j_lo in range(1, n_bin + 1):
        asw_in = 0.0
        assw_in = 0.0
        for j_up in range(j_lo, n_bin + 1):
            asw_in += content[j_up - 1]
            assw_in += errors[j_up - 1]
            x_lo = (j_lo - 1.0) / n_bin
            x_up = (j_up * 1.0) / n_bin
            inside = _spread(assw_in, nent, x_up - x_lo)
            spread = inside + _spread(ssw_all - assw_in, nent, 1.0 - x_up + x_lo)
            if spread < best:
                best, x_min, x_max = spread, x_lo, x_up
    return best, x_min, x_max


def _spread(assw: float, nent: float, width: float) -> Any:
    """``sqrt(assw) / sqrt(nent * width) * width``, NaN where ROOT's is."""
    w = np.float64(width)
    return np.sqrt(np.float64(assw)) / np.sqrt(np.float64(nent) * w) * w


class FoamGenerator:
    """``RooFoamGenerator``: FOAM over the observables' ranges, with RooFit's settings.

    ``function`` is what ``RooTFoamBinding`` evaluates: the pdf, normalised
    over the generated observables, at a point of the observables' own
    coordinates. By default it is called with one point at a time, a 1-D
    array of ``dim`` coordinates, and returns a number; with
    ``vectorized=True`` it is called with an array of points, shape
    ``(n, dim)``, and returns ``n`` numbers. Negative values count as zero,
    as the binding makes them. ``ranges`` is one ``(low, high)`` per
    observable, in RooFit's order of the observables.

    For RooFit's events to the last bit, the values must be RooFit's: the
    pdf's value divided by its normalisation integral, computed as RooFit
    computes both. A multiple of it builds a foam just as good, but not
    always the same one.

    ``rng`` must be the generator RooFit draws from, ``RooRandom::randomGenerator()``
    - a ``TRandom3`` with the default seed, not ``gRandom`` - in the state
    RooFit's is in. The foam is built here, which is when RooFit builds it:
    when the generator is made, before the first event is asked for. The
    cells default to ``nCell1D``, ``nCell2D``, ``nCell3D`` or ``nCellND``
    by the dimension; ``n_sample`` is ``nSample``.
    """

    def __init__(
        self, function: Callable[[Any], Any], ranges: Any, rng: Any = None, *,
        vectorized: bool = False, n_cells: int | None = None,
        n_sample: int = ROOFIT_SAMPLES,
    ) -> None:
        bounds = np.asarray(ranges, dtype=np.float64).reshape(-1, 2)
        self.low = bounds[:, 0].copy()
        self.high = bounds[:, 1].copy()
        self.range = self.high - self.low
        self.function = function
        self.vectorized = vectorized
        dim = len(self.low)
        if n_cells is None:
            n_cells = ROOFIT_CELLS.get(dim, ROOFIT_CELLS_ND)
        self.foam = Foam(
            self._density, dim, TRandom3() if rng is None else rng,
            n_cells=n_cells, n_sampl=n_sample,
        )
        self.foam.initialize()

    def _density(self, unit: Any) -> Any:
        """``RooTFoamBinding::Density``: the function at the points mapped onto the ranges."""
        points = unit * (self.high - self.low) + self.low
        if self.vectorized:
            values = np.asarray(self.function(points), dtype=np.float64)
        else:
            values = np.array([float(self.function(point)) for point in points])
        return np.where(values < 0, 0.0, values)

    def generate(self) -> Any:
        """``generateEvent``: the next event, one value per observable."""
        return self.low + self.range * self.foam.make_event()

    def generate_many(self, count: int) -> Any:
        """The next ``count`` events, one row each, made one after another."""
        rows = [self.generate() for _ in range(count)]
        return np.array(rows).reshape(count, len(self.low))
