"""The help each method prints when booked with ``H``: TMVA's own words, as it prints them.

``GetHelpMessage`` of each TMVA method, line for line - ``{bold}`` and
``{reset}`` are where TMVA switches to bold and back, which is only when
colour is on - framed as ``MethodBase::PrintHelpMessage`` frames it.
"""

from __future__ import annotations

from .log import Logger, color

__all__ = ["HELP", "print_help"]

#: Each method's help, by its type name.
HELP: dict[str, tuple[str, ...]] = {
    "LD": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "Linear discriminants select events by distinguishing the mean ",
        "values of the signal and background distributions in a trans- ",
        "formed variable space where linear correlations are removed.",
        'The LD implementation here is equivalent to the "Fisher" discriminant',
        "for classification, but also provides linear regression.",
        "",
        '   (More precisely: the "linear discriminator" determines',
        "    an axis in the (correlated) hyperspace of the input ",
        "    variables such that, when projecting the output classes ",
        "    (signal and background) upon this axis, they are pushed ",
        "    as far as possible away from each other, while events",
        "    of a same class are confined in a close vicinity. The  ",
        "    linearity property of this classifier is reflected in the ",
        '    metric with which "far apart" and "close vicinity" are ',
        "    determined: the covariance matrix of the discriminating",
        "    variable space.)",
        "",
        "{bold}--- Performance optimisation:{reset}",
        "",
        "Optimal performance for the linear discriminant is obtained for ",
        "linearly correlated Gaussian-distributed variables. Any deviation",
        "from this ideal reduces the achievable separation power. In ",
        "particular, no discrimination at all is achieved for a variable",
        "that has the same sample mean for signal and background, even if ",
        "the shapes of the distributions are very different. Thus, the linear ",
        "discriminant often benefits from a suitable transformation of the ",
        "input variables. For example, if a variable x in [-1,1] has a ",
        "a parabolic signal distributions, and a uniform background",
        "distributions, their mean value is zero in both cases, leading ",
        "to no separation. The simple transformation x -> |x| renders this ",
        "variable powerful for the use in a linear discriminant.",
        "",
        "{bold}--- Performance tuning via configuration options:{reset}",
        "",
        "<None>",
    ),
    "Fisher": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "Fisher discriminants select events by distinguishing the mean ",
        "values of the signal and background distributions in a trans- ",
        "formed variable space where linear correlations are removed.",
        "",
        '   (More precisely: the "linear discriminator" determines',
        "    an axis in the (correlated) hyperspace of the input ",
        "    variables such that, when projecting the output classes ",
        "    (signal and background) upon this axis, they are pushed ",
        "    as far as possible away from each other, while events",
        "    of a same class are confined in a close vicinity. The  ",
        "    linearity property of this classifier is reflected in the ",
        '    metric with which "far apart" and "close vicinity" are ',
        "    determined: the covariance matrix of the discriminating",
        "    variable space.)",
        "",
        "{bold}--- Performance optimisation:{reset}",
        "",
        "Optimal performance for Fisher discriminants is obtained for ",
        "linearly correlated Gaussian-distributed variables. Any deviation",
        "from this ideal reduces the achievable separation power. In ",
        "particular, no discrimination at all is achieved for a variable",
        "that has the same sample mean for signal and background, even if ",
        "the shapes of the distributions are very different. Thus, Fisher ",
        "discriminants often benefit from suitable transformations of the ",
        "input variables. For example, if a variable x in [-1,1] has a ",
        "a parabolic signal distributions, and a uniform background",
        "distributions, their mean value is zero in both cases, leading ",
        "to no separation. The simple transformation x -> |x| renders this ",
        "variable powerful for the use in a Fisher discriminant.",
        "",
        "{bold}--- Performance tuning via configuration options:{reset}",
        "",
        "<None>",
    ),
    "Likelihood": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "The maximum-likelihood classifier models the data with probability ",
        "density functions (PDF) reproducing the signal and background",
        "distributions of the input variables. Correlations among the ",
        "variables are ignored.",
        "",
        "{bold}--- Performance optimisation:{reset}",
        "",
        "Required for good performance are decorrelated input variables",
        '(PCA transformation via the option "VarTransform=Decorrelate"',
        "may be tried). Irreducible non-linear correlations may be reduced",
        "by precombining strongly correlated input variables, or by simply",
        "removing one of the variables.",
        "",
        "{bold}--- Performance tuning via configuration options:{reset}",
        "",
        "High fidelity PDF estimates are mandatory, i.e., sufficient training ",
        "statistics is required to populate the tails of the distributions",
        "It would be a surprise if the default Spline or KDE kernel parameters",
        "provide a satisfying fit to the data. The user is advised to properly",
        "tune the events per bin and smooth options in the spline cases",
        "individually per variable. If the KDE kernel is used, the adaptive",
        "Gaussian kernel may lead to artefacts, so please always also try",
        "the non-adaptive one.",
        "",
        "All tuning parameters must be adjusted individually for each input",
        "variable!",
    ),
    "KNN": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "The k-nearest neighbor (k-NN) algorithm is a multi-dimensional classification",
        "and regression algorithm. Similarly to other TMVA algorithms, k-NN uses a set of",
        "training events for which a classification category/regression target is known. ",
        "The k-NN method compares a test event to all training events using a distance ",
        "function, which is an Euclidean distance in a space defined by the input variables. ",
        "The k-NN method, as implemented in TMVA, uses a kd-tree algorithm to perform a",
        "quick search for the k events with shortest distance to the test event. The method",
        "returns a fraction of signal events among the k neighbors. It is recommended",
        "that a histogram which stores the k-NN decision variable is binned with k+1 bins",
        "between 0 and 1.",
        "",
        "{bold}--- Performance tuning via configuration options: {reset}",
        "",
        "The k-NN method estimates a density of signal and background events in a ",
        "neighborhood around the test event. The method assumes that the density of the ",
        "signal and background events is uniform and constant within the neighborhood. ",
        "k is an adjustable parameter and it determines an average size of the ",
        "neighborhood. Small k values (less than 10) are sensitive to statistical ",
        "fluctuations and large (greater than 100) values might not sufficiently capture  ",
        "local differences between events in the training set. The speed of the k-NN",
        "method also increases with larger values of k. ",
        "",
        "The k-NN method assigns equal weight to all input variables. Different scales ",
        "among the input variables is compensated using ScaleFrac parameter: the input ",
        "variables are scaled so that the widths for central ScaleFrac*100% events are ",
        "equal among all the input variables.",
        "",
        "{bold}--- Additional configuration options: {reset}",
        "",
        "The method inclues an option to use a Gaussian kernel to smooth out the k-NN",
        "response. The kernel re-weights events using a distance to the test event.",
    ),
    "FDA": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "The function discriminant analysis (FDA) is a classifier suitable ",
        "to solve linear or simple nonlinear discrimination problems.",
        "",
        "The user provides the desired function with adjustable parameters",
        "via the configuration option string, and FDA fits the parameters to",
        "it, requiring the signal (background) function value to be as close",
        "as possible to 1 (0). Its advantage over the more involved and",
        "automatic nonlinear discriminators is the simplicity and transparency ",
        "of the discrimination expression. A shortcoming is that FDA will",
        "underperform for involved problems with complicated, phase space",
        "dependent nonlinear correlations.",
        "",
        "Please consult the Users Guide for the format of the formula string",
        "and the allowed parameter ranges:",
        "documentation/tmva/UsersGuide/TMVAUsersGuide.pdf",
        "",
        "{bold}--- Performance optimisation:{reset}",
        "",
        "The FDA performance depends on the complexity and fidelity of the",
        "user-defined discriminator function. As a general rule, it should",
        "be able to reproduce the discrimination power of any linear",
        "discriminant analysis. To reach into the nonlinear domain, it is",
        "useful to inspect the correlation profiles of the input variables,",
        "and add quadratic and higher polynomial terms between variables as",
        "necessary. Comparison with more involved nonlinear classifiers can",
        "be used as a guide.",
        "",
        "{bold}--- Performance tuning via configuration options:{reset}",
        "",
        'Depending on the function used, the choice of "FitMethod" is',
        "crucial for getting valuable solutions with FDA. As a guideline it",
        'is recommended to start with "FitMethod=MINUIT". When more complex',
        "functions are used where MINUIT does not converge to reasonable",
        "results, the user should switch to non-gradient FitMethods such",
        "as GeneticAlgorithm (GA) or Monte Carlo (MC). It might prove to be",
        "useful to combine GA (or MC) with MINUIT by setting the option",
        '"Converger=MINUIT". GA (MC) will then set the starting parameters',
        "for MINUIT such that the basic quality of GA (MC) of finding global",
        "minima is combined with the efficacy of MINUIT of finding local",
        "minima.",
    ),
    "MLP": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "The MLP artificial neural network (ANN) is a traditional feed-",
        "forward multilayer perceptron implementation. The MLP has a user-",
        "defined hidden layer architecture, while the number of input (output)",
        "nodes is determined by the input variables (output classes, i.e., ",
        "signal and one background). ",
        "",
        "{bold}--- Performance optimisation:{reset}",
        "",
        "Neural networks are stable and performing for a large variety of ",
        "linear and non-linear classification problems. However, in contrast",
        "to (e.g.) boosted decision trees, the user is advised to reduce the ",
        "number of input variables that have only little discrimination power. ",
        "",
        "In the tests we have carried out so far, the MLP and ROOT networks",
        "(TMlpANN, interfaced via TMVA) performed equally well, with however",
        "a clear speed advantage for the MLP. The Clermont-Ferrand neural ",
        "net (CFMlpANN) exhibited worse classification performance in these",
        "tests, which is partly due to the slow convergence of its training",
        "(at least 10k training cycles are required to achieve approximately",
        "competitive results).",
        "",
        "{bold}Overtraining: {reset}only the TMlpANN performs an explicit separation of the",
        "full training sample into independent training and validation samples.",
        "We have found that in most high-energy physics applications the ",
        "available degrees of freedom (training events) are sufficient to ",
        "constrain the weights of the relatively simple architectures required",
        "to achieve good performance. Hence no overtraining should occur, and ",
        "the use of validation samples would only reduce the available training",
        "information. However, if the performance on the training sample is ",
        "found to be significantly better than the one found with the inde-",
        "pendent test sample, caution is needed. The results for these samples ",
        "are printed to standard output at the end of each training job.",
        "",
        "{bold}--- Performance tuning via configuration options:{reset}",
        "",
        "The hidden layer architecture for all ANNs is defined by the option",
        '"HiddenLayers=N+1,N,...", where here the first hidden layer has N+1',
        "neurons and the second N neurons (and so on), and where N is the number  ",
        "of input variables. Excessive numbers of hidden layers should be avoided,",
        "in favour of more neurons in the first hidden layer.",
        "",
        "The number of cycles should be above 500. As said, if the number of",
        "adjustable weights is small compared to the training sample size,",
        "using a large number of training samples should not lead to overtraining.",
    ),
    "SVM": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "The Support Vector Machine (SVM) builds a hyperplane separating",
        "signal and background events (vectors) using the minimal subset of ",
        "all vectors used for training (support vectors). The extension to",
        "the non-linear case is performed by mapping input vectors into a ",
        "higher-dimensional feature space in which linear separation is ",
        "possible. The use of the kernel functions thereby eliminates the ",
        "explicit transformation to the feature space. The implemented SVM ",
        "algorithm performs the classification tasks using linear, polynomial, ",
        "Gaussian and sigmoidal kernel functions. The Gaussian kernel allows ",
        "to apply any discriminant shape in the input space.",
        "",
        "{bold}--- Performance optimisation:{reset}",
        "",
        "SVM is a general purpose non-linear classification method, which ",
        "does not require data preprocessing like decorrelation or Principal ",
        "Component Analysis. It generalises quite well and can handle analyses ",
        "with large numbers of input variables.",
        "",
        "{bold}--- Performance tuning via configuration options:{reset}",
        "",
        "Optimal performance requires primarily a proper choice of the kernel ",
        'parameters (the width "Sigma" in case of Gaussian kernel) and the',
        'cost parameter "C". The user must optimise them empirically by running',
        "SVM several times with different parameter sets. The time needed for ",
        "each evaluation scales like the square of the number of training ",
        "events so that a coarse preliminary tuning should be performed on ",
        "reduced data sets.",
    ),
    "BDT": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "Boosted Decision Trees are a collection of individual decision",
        "trees which form a multivariate classifier by (weighted) majority ",
        "vote of the individual trees. Consecutive decision trees are  ",
        "trained using the original training data set with re-weighted ",
        "events. By default, the AdaBoost method is employed, which gives ",
        "events that were misclassified in the previous tree a larger ",
        "weight in the training of the following tree.",
        "",
        "Decision trees are a sequence of binary splits of the data sample",
        "using a single discriminant variable at a time. A test event ",
        "ending up after the sequence of left-right splits in a final ",
        '("leaf") node is classified as either signal or background',
        "depending on the majority type of training events in that node.",
        "",
        "{bold}--- Performance optimisation:{reset}",
        "",
        "By the nature of the binary splits performed on the individual",
        "variables, decision trees do not deal well with linear correlations",
        "between variables (they need to approximate the linear split in",
        "the two dimensional space by a sequence of splits on the two ",
        "variables individually). Hence decorrelation could be useful ",
        "to optimise the BDT performance.",
        "",
        "{bold}--- Performance tuning via configuration options:{reset}",
        "",
        "The two most important parameters in the configuration are the  ",
        "minimal number of events requested by a leaf node as percentage of the ",
        '   number of training events (option "MinNodeSize"  replacing the actual number ',
        ' of events "nEventsMin" as given in earlier versions',
        "If this number is too large, detailed features ",
        "in the parameter space are hard to be modelled. If it is too small, ",
        "the risk to overtrain rises and boosting seems to be less effective",
        "  typical values from our current experience for best performance  ",
        "  are between 0.5(%) and 10(%) ",
        "",
        "The default minimal number is currently set to ",
        "   max(20, (N_training_events / N_variables^2 / 10)) ",
        "and can be changed by the user.",
        "",
        'The other crucial parameter, the pruning strength ("PruneStrength"),',
        "is also related to overtraining. It is a regularisation parameter ",
        "that is used when determining after the training which splits ",
        "are considered statistically insignificant and are removed. The",
        "user is advised to carefully watch the BDT screen output for",
        "the comparison between efficiencies obtained on the training and",
        "the independent test sample. They should be equal within statistical",
        "errors, in order to minimize statistical fluctuations in different samples.",
    ),
    "RuleFit": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "This method uses a collection of so called rules to create a",
        "discriminating scoring function. Each rule consists of a series",
        "of cuts in parameter space. The ensemble of rules are created",
        "from a forest of decision trees, trained using the training data.",
        "Each node (apart from the root) corresponds to one rule.",
        "The scoring function is then obtained by linearly combining",
        "the rules. A fitting procedure is applied to find the optimum",
        "set of coefficients. The goal is to find a model with few rules",
        "but with a strong discriminating power.",
        "",
        "{bold}--- Performance optimisation:{reset}",
        "",
        "There are two important considerations to make when optimising:",
        "",
        "  1. Topology of the decision tree forest",
        "  2. Fitting of the coefficients",
        "",
        "The maximum complexity of the rules is defined by the size of",
        "the trees. Large trees will yield many complex rules and capture",
        "higher order correlations. On the other hand, small trees will",
        "lead to a smaller ensemble with simple rules, only capable of",
        "modeling simple structures.",
        "Several parameters exists for controlling the complexity of the",
        "rule ensemble.",
        "",
        "The fitting procedure searches for a minimum using a gradient",
        "directed path. Apart from step size and number of steps, the",
        "evolution of the path is defined by a cut-off parameter, tau.",
        "This parameter is unknown and depends on the training data.",
        "A large value will tend to give large weights to a few rules.",
        "Similarly, a small value will lead to a large set of rules",
        "with similar weights.",
        "",
        "A final point is the model used; rules and/or linear terms.",
        "For a given training sample, the result may improve by adding",
        "linear terms. If best performance is obtained using only linear",
        "terms, it is very likely that the Fisher discriminant would be",
        "a better choice. Ideally the fitting procedure should be able to",
        "make this choice by giving appropriate weights for either terms.",
        "",
        "{bold}--- Performance tuning via configuration options:{reset}",
        "",
        "I.  TUNING OF RULE ENSEMBLE:",
        "",
        '   {bold}ForestType  {reset}: Recommended is to use the default "AdaBoost".',
        "   {bold}nTrees      {reset}: More trees leads to more rules but also slow",
        "                 performance. With too few trees the risk is",
        "                 that the rule ensemble becomes too simple.",
        "   {bold}fEventsMin  {reset}",
        "   {bold}fEventsMax  {reset}: With a lower min, more large trees will be generated",
        "                 leading to more complex rules.",
        "                 With a higher max, more small trees will be",
        "                 generated leading to more simple rules.",
        "                 By changing this range, the average complexity",
        "                 of the rule ensemble can be controlled.",
        "   {bold}RuleMinDist {reset}: By increasing the minimum distance between",
        "                 rules, fewer and more diverse rules will remain.",
        "                 Initially it is a good idea to keep this small",
        "                 or zero and let the fitting do the selection of",
        "                 rules. In order to reduce the ensemble size,",
        "                 the value can then be increased.",
        "",
        "II. TUNING OF THE FITTING:",
        "",
        "   {bold}GDPathEveFrac {reset}: fraction of events in path evaluation",
        "                 Increasing this fraction will improve the path",
        "                 finding. However, a too high value will give few",
        "                 unique events available for error estimation.",
        "                 It is recommended to use the default = 0.5.",
        "   {bold}GDTau         {reset}: cutoff parameter tau",
        "                 By default this value is set to -1.0.",
        "                 This means that the cut off parameter is",
        "                 automatically estimated. In most cases",
        "                 this should be fine. However, you may want",
        "                 to fix this value if you already know it",
        "                 and want to reduce on training time.",
        "   {bold}GDTauPrec     {reset}: precision of estimated tau",
        "                 Increase this precision to find a more",
        "                 optimum cut-off parameter.",
        "   {bold}GDNStep       {reset}: number of steps in path search",
        "                 If the number of steps is too small, then",
        "                 the program will give a warning message.",
        "",
        "III. WARNING MESSAGES",
        "",
        "{bold}Risk(i+1)>=Risk(i) in path{reset}",
        "{bold}Chaotic behaviour of risk evolution.{reset}",
        "                 The error rate was still decreasing at the end",
        "                 By construction the Risk should always decrease.",
        "                 However, if the training sample is too small or",
        "                 the model is overtrained, such warnings can",
        "                 occur.",
        "                 The warnings can safely be ignored if only a",
        "                 few (<3) occur. If more warnings are generated,",
        "                 the fitting fails.",
        "                 A remedy may be to increase the value",
        "                 {bold}GDValidEveFrac{reset} to 1.0 (or a larger value).",
        "                 In addition, if {bold}GDPathEveFrac{reset} is too high",
        "                 the same warnings may occur since the events",
        "                 used for error estimation are also used for",
        "                 path estimation.",
        "                 Another possibility is to modify the model - ",
        "                 See above on tuning the rule ensemble.",
        "",
        "{bold}The error rate was still decreasing at the end of the path{reset}",
        "                 Too few steps in path! Increase {bold}GDNSteps{reset}.",
        "",
        "{bold}Reached minimum early in the search{reset}",
        "                 Minimum was found early in the fitting. This",
        "                 may indicate that the used step size {bold}GDStep{reset}.",
        "                 was too large. Reduce it and rerun.",
        "                 If the results still are not OK, modify the",
        "                 model either by modifying the rule ensemble",
        "                 or add/remove linear terms",
    ),
    "Cuts": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "The optimisation of rectangular cuts performed by TMVA maximises ",
        "the background rejection at given signal efficiency, and scans ",
        "over the full range of the latter quantity. Three optimisation",
        "methods are optional: Monte Carlo sampling (MC), a Genetics",
        "Algorithm (GA), and Simulated Annealing (SA). GA and SA are",
        "expected to perform best.",
        "",
        "The difficulty to find the optimal cuts strongly increases with",
        "the dimensionality (number of input variables) of the problem.",
        "This behavior is due to the non-uniqueness of the solution space.",
        "",
        "{bold}--- Performance optimisation:{reset}",
        "",
        "If the dimensionality exceeds, say, 4 input variables, it is ",
        "advisable to scrutinize the separation power of the variables,",
        "and to remove the weakest ones. If some among the input variables",
        "can be described by a single cut (e.g., because signal tends to be",
        "larger than background), this can be indicated to MethodCuts via",
        'the "Fsmart" options (see option string). Choosing this option',
        "reduces the number of requirements for the variable from 2 (min/max)",
        "to a single one (TMVA finds out whether it is to be interpreted as",
        "min or max).",
        "",
        "{bold}--- Performance tuning via configuration options:{reset}",
        "",
        "Monte Carlo sampling:",
        "",
        'Apart form the "Fsmart" option for the variables, the only way',
        "to improve the MC sampling is to increase the sampling rate. This",
        'is done via the configuration option "MC_NRandCuts". The execution',
        "time scales linearly with the sampling rate.",
        "",
        "Genetic Algorithm:",
        "",
        "The algorithm terminates if no significant fitness increase has",
        'been achieved within the last "nsteps" steps of the calculation.',
        "Wiggles in the ROC curve or constant background rejection of 1",
        "indicate that the GA failed to always converge at the true maximum",
        "fitness. In such a case, it is recommended to broaden the search ",
        'by increasing the population size ("popSize") and to give the GA ',
        "more time to find improvements by increasing the number of steps",
        '("nsteps")',
        '  -> increase "popSize" (at least >10 * number of variables)',
        '  -> increase "nsteps"',
        "",
        "Simulated Annealing (SA) algorithm:",
        "",
        '"Increasing Adaptive" approach:',
        "",
        "The algorithm seeks local minima and explores their neighborhoods, while",
        "changing the ambient temperature depending on the number of failures",
        "in the previous steps. The performance can be improved by increasing",
        'the number of iteration steps ("MaxCalls"), or by adjusting the',
        'minimal temperature ("MinTemperature"). Manual adjustments of the',
        'speed of the temperature increase ("TemperatureScale" and "AdaptiveSpeed")',
        "to individual data sets should also help. Summary:",
        '  -> increase "MaxCalls"',
        '  -> adjust   "MinTemperature"',
        '  -> adjust   "TemperatureScale"',
        '  -> adjust   "AdaptiveSpeed"',
        "",
        '"Decreasing Adaptive" approach:',
        "",
        "The algorithm calculates the initial temperature (based on the effect-",
        "iveness of large steps) and the multiplier that ensures to reach the",
        "minimal temperature with the requested number of iteration steps.",
        "The performance can be improved by adjusting the minimal temperature",
        ' ("MinTemperature") and by increasing number of steps ("MaxCalls"):',
        '  -> increase "MaxCalls"',
        '  -> adjust   "MinTemperature"',
        " ",
        "Other kernels:",
        "",
        "Alternative ways of counting the temperature change are implemented. ",
        'Each of them starts with the maximum temperature ("MaxTemperature")',
        "and decreases while changing the temperature according to a given",
        "prescription:",
        "CurrentTemperature =",
        "  - Sqrt: InitialTemperature / Sqrt(StepNumber+2) * TemperatureScale",
        "  - Log:  InitialTemperature / Log(StepNumber+2) * TemperatureScale",
        "  - Homo: InitialTemperature / (StepNumber+2) * TemperatureScale",
        "  - Sin:  (Sin(StepNumber / TemperatureScale) + 1) / (StepNumber + 1)"
        "*InitialTemperature + Eps",
        "  - Geo:  CurrentTemperature * TemperatureScale",
        "",
        "Their performance can be improved by adjusting initial temperature",
        '("InitialTemperature"), the number of iteration steps ("MaxCalls"),',
        "and the multiplier that scales the temperature decrease",
        '("TemperatureScale")',
        '  -> increase "MaxCalls"',
        '  -> adjust   "InitialTemperature"',
        '  -> adjust   "TemperatureScale"',
        '  -> adjust   "KernelTemperature"',
    ),
    "PDERS": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "PDERS is a generalization of the projective likelihood classifier ",
        "to N dimensions, where N is the number of input variables used.",
        "In its adaptive form it is mostly equivalent to k-Nearest-Neighbor",
        "(k-NN) methods. If the multidimensional PDF for signal and background",
        "were known, this classifier would exploit the full information",
        "contained in the input variables, and would hence be optimal. In ",
        "practice however, huge training samples are necessary to sufficiently ",
        "populate the multidimensional phase space. ",
        "",
        "The simplest implementation of PDERS counts the number of signal",
        "and background events in the vicinity of a test event, and returns",
        "a weight according to the majority species of the neighboring events.",
        'A more involved version of PDERS (selected by the option "KernelEstimator")',
        "uses Kernel estimation methods to approximate the shape of the PDF.",
        "",
        "{bold}--- Performance optimisation:{reset}",
        "",
        "PDERS can be very powerful in case of strongly non-linear problems, ",
        "e.g., distinct islands of signal and background regions. Because of ",
        "the exponential growth of the phase space, it is important to restrict",
        "the number of input variables (dimension) to the strictly necessary.",
        "",
        "Note that PDERS is a slowly responding classifier. Moreover, the necessity",
        "to store the entire binary tree in memory, to avoid accessing virtual ",
        "memory, limits the number of training events that can effectively be ",
        "used to model the multidimensional PDF.",
        "",
        "{bold}--- Performance tuning via configuration options:{reset}",
        "",
        "If the PDERS response is found too slow when using the adaptive volume ",
        'size (option "VolumeRangeMode=Adaptive"), it might be found beneficial',
        "to reduce the number of events required in the volume, and/or to enlarge",
        'the allowed range ("NeventsMin/Max"). PDERS is relatively insensitive',
        'to the width ("GaussSigma") of the Gaussian kernel (if used).',
    ),
    "PDEFoam": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "PDE-Foam is a variation of the PDE-RS method using a self-adapting",
        "binning method to divide the multi-dimensional variable space into a",
        "finite number of hyper-rectangles (cells). The binning algorithm ",
        "adjusts the size and position of a predefined number of cells such",
        "that the variance of the signal and background densities inside the ",
        "cells reaches a minimum",
        "",
        "{bold}--- Use of booking options:{reset}",
        "",
        "The PDEFoam classifier supports two different algorithms: ",
        "",
        "  (1) Create one foam, which stores the signal over background",
        "      probability density.  During foam buildup the variance of the",
        "      discriminant inside the cells is minimised.",
        "",
        "      Booking option:   SigBgSeparated=F",
        "",
        "  (2) Create two separate foams, one for the signal events and one for",
        "      background events.  During foam buildup the variance of the",
        "      event density inside the cells is minimised separately for",
        "      signal and background.",
        "",
        "      Booking option:   SigBgSeparated=T",
        "",
        "The following options can be set (the listed values are found to be a",
        "good starting point for most applications):",
        "",
        "        SigBgSeparate   False   Separate Signal and Background",
        "              TailCut   0.001   Fraction of outlier events that excluded",
        "                                from the foam in each dimension ",
        "              VolFrac  0.0666   Volume fraction (used for density calculation",
        "                                during foam build-up) ",
        "         nActiveCells     500   Maximal number of active cells in final foam ",
        "               nSampl    2000   Number of MC events per cell in foam build-up ",
        "                 nBin       5   Number of bins used in foam build-up ",
        "                 Nmin     100   Number of events in cell required to split cell",
        "               Kernel    None   Kernel type used (possible values are: None,",
        "                                Gauss)",
        "             Compress    True   Compress foam output file ",
        "",
        "   Additional regression options:",
        "",
        "MultiTargetRegression   False   Do regression with multiple targets ",
        "      TargetSelection    Mean   Target selection method (possible values are: ",
        "                                Mean, Mpv)",
        "",
        "{bold}--- Performance optimisation:{reset}",
        "",
        "The performance of the two implementations was found to be similar for",
        "most examples studied. For the same number of cells per foam, the two-",
        "foam option approximately doubles the amount of computer memory needed",
        "during classification. For special cases where the event-density",
        "distribution of signal and background events is very different, the",
        "two-foam option was found to perform significantly better than the",
        "option with only one foam.",
        "",
        "In order to gain better classification performance we recommend to set",
        'the parameter "nActiveCells" to a high value.',
        "",
        'The parameter "VolFrac" specifies the size of the sampling volume',
        "during foam buildup and should be tuned in order to achieve optimal",
        "performance.  A larger box leads to a reduced statistical uncertainty",
        "for small training samples and to smoother sampling. A smaller box on",
        "the other hand increases the sensitivity to statistical fluctuations",
        "in the training samples, but for sufficiently large training samples",
        "it will result in a more precise local estimate of the sampled",
        "density. In general, higher dimensional problems require larger box",
        "sizes, due to the reduced average number of events per box volume. The",
        "default value of 0.0666 was optimised for an example with 5",
        "observables and training samples of the order of 50000 signal and",
        "background events each.",
        "",
        "Furthermore kernel weighting can be activated, which will lead to an",
        "additional performance improvement. Note that Gauss weighting will",
        "significantly increase the response time of the method. LinNeighbors",
        "weighting performs a linear interpolation with direct neighbor cells",
        "for each dimension and is much faster than Gauss weighting.",
        "",
        "The classification results were found to be rather insensitive to the",
        'values of the parameters "nSamples" and "nBin".',
    ),
    "HMatrix": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "The H-Matrix classifier discriminates one class (signal) of a feature",
        "vector from another (background). The correlated elements of the",
        "vector are assumed to be Gaussian distributed, and the inverse of",
        "the covariance matrix is the H-Matrix. A multivariate chi-squared",
        "estimator is built that exploits differences in the mean values of",
        "the vector elements between the two classes for the purpose of",
        "discrimination.",
        "",
        "{bold}--- Performance optimisation:{reset}",
        "",
        "The TMVA implementation of the H-Matrix classifier has been shown",
        "to underperform in comparison with the corresponding Fisher discriminant,",
        "when using similar assumptions and complexity. Its use is therefore",
        "depreciated. Only in cases where the background model is strongly",
        "non-Gaussian, H-Matrix may perform better than Fisher. In such",
        "occurrences the user is advised to employ non-linear classifiers. ",
        "",
        "{bold}--- Performance tuning via configuration options:{reset}",
        "",
        "None",
    ),
    "Category": (
        "",
        "{bold}--- Short description:{reset}",
        "",
        "This method allows to define different categories of events. The",
        "categories are defined via cuts on the variables. For each",
        "category, a different classifier and set of variables can be",
        "specified. The categories which are defined for this method must",
        "be disjoint.",
    ),
}


#: The rule the help is framed by.
RULE = "=" * 64


def _coloured(line: str) -> str:
    return line.replace("{bold}", color("bold")).replace("{reset}", color("reset"))


def print_help(log: Logger, type_name: str, name: str) -> None:
    """``PrintHelpMessage``: the framed help of a method of ``type_name`` called ``name``."""
    bold, reset = color("bold"), color("reset")
    log.info("")
    log.info(f"{bold}{RULE}{reset}")
    log.info(f"{bold}H e l p   f o r   M V A   m e t h o d   [ {name} ] :{reset}")
    for line in HELP.get(type_name, ()):
        log.info(_coloured(line))
    log.info("")
    log.info('<Suppress this message by specifying "!H" in the booking option>')
    log.info(f"{bold}{RULE}{reset}")
    log.info("")
