"""What the classes this library writes look like, harvested rather than typed.

Every entry here was read out of the streamer information ROOT itself wrote
into the files under ``tests/data``, by a walk of the same records
``read_streamers`` reads. The tree, graph and collection classes come from
``gauss-h1.root``, ``gauss-h2.root``, ``graphs.root`` and
``small-flat-tree.root``, all written by ROOT 6.08; three leaf classes no 6.08
donor happens to contain - ``TLeafO``, ``TLeafB`` and ``TLeafS`` - come from
``leaves.root`` instead, which ROOT 6.28 wrote, and the two vintages describe
every leaf class they share identically down to the checksum.

The histogram family is one vintage newer. A profile, an efficiency and a
three-dimensional histogram have no 6.08 donor here, and a ``TProfile`` built
on one ``TH1D`` beside a ``TH1F`` built on another would be a file describing
two different ``TH1`` classes by the one name. So all of it comes from files
ROOT 6.22 and 6.24 wrote: ``TH1``, ``TH1D``, ``TH2``, ``TH2D``, ``TProfile``
and ``TProfile2D`` from ``tprofile.root``, ``TH1F`` from ``tgme.root``,
``TEfficiency`` from ``tconfidence-level.root``, and ``TH3``, ``TH3D``,
``TAtt3D`` and ``TProfile3D`` from ``uproot-issue-227b.root``. That vintage
adds ``fStatOverflows`` to the end of ``TH1``, where a reader of the older
layout steps over it.

The functions a fit is made with are of that vintage too, and from the same
donors: ``TF1``, ``TFormula`` and ``TF1Parameters`` from ``tgme.root`` - whose
``TMultiGraph`` ROOT fitted with a ``pol1`` - and ``TF1AbsComposition``,
which ``tgme.root`` never needed, from ``tformula.root``, which ROOT 6.24
wrote as well. That ``TFormula`` is version 13, the last without
``fNumber``; ROOT 6.34 reads it. ``TF2`` and ``TF3`` have no donor here at
all, so they are read - a file describes them - but not written.

Eleven histogram classes - ``TH1C``, ``TH1S`` and ``TH1I``, the same three
and ``TH2F`` in two dimensions, and the other four ``TH3`` classes - have no
donor of that vintage here. Each is nothing but two bases, a ``TH1``, ``TH2``
or ``TH3`` and the ``TArray`` it keeps its bins in, so its elements are those
bases exactly as the harvested classes carry them, and its checksum is what
ROOT's ``TClass::GetCheckSum`` makes of them: the class name, then each base's
name and checksum. That calculation reproduces every harvested checksum in
this table, which the tests hold it to, and the seven of the eleven that
ROOT's own streamer dump in go-hep contains come out as ROOT has them.

Writing carries these descriptions back out verbatim, checksums and all, so a
file written here says exactly what a ROOT of that vintage would say about the
same classes, and anything reading it - ROOT, this library, or another - walks
the bytes by the same map they were written from.

Regenerate from the donor files rather than editing: a hand-edited layout is a
guess, and a guess about layout is how physics data gets misread.
"""

from __future__ import annotations

__all__ = ["INFOS", "SUBVERSIONS", "WRITER_VERSION"]

#: The ROOT version the donor descriptions came from, written into the header.
WRITER_VERSION = 60806

#: The record version each ``TStreamerElement`` subclass wrote itself with.
SUBVERSIONS = {
    "TStreamerBase": 3,
    "TStreamerBasicType": 2,
    "TStreamerBasicPointer": 2,
    "TStreamerString": 2,
    "TStreamerObject": 2,
    "TStreamerObjectAny": 2,
    "TStreamerObjectPointer": 2,
    "TStreamerObjectAnyPointer": 1,
    "TStreamerSTL": 3,
}

#: One element of one class: its ``TStreamerElement`` subclass, name, title,
#: streamer type, size, array length, array dimensions, the five maximum
#: indices, the type name, and whatever extra fields the subclass adds - the
#: base class version for a ``TStreamerBase``, the counter's version, name
#: and class for a ``TStreamerBasicPointer``, and the kind of container and
#: of what it holds for a ``TStreamerSTL``.
Element = tuple[str, str, str, int, int, int, int, tuple[int, ...], str, tuple[object, ...]]

#: Every class this library can write: its checksum, version and elements,
#: exactly as the donor files describe them.
INFOS: dict[str, tuple[int, int, tuple[Element, ...]]] = {
    "TH1C": (0x36f6e4ad, 3, (
        ('TStreamerBase', 'TH1', '1-Dim histogram base class',
         0, 0, 0, 0, (0, 473383108, 0, 0, 0), 'BASE', (8,)),
        ('TStreamerBase', 'TArrayC', 'Array of chars',
         0, 0, 0, 0, (0, -1366845130, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH1S": (0x8c4d9dcb, 3, (
        ('TStreamerBase', 'TH1', '1-Dim histogram base class',
         0, 0, 0, 0, (0, 473383108, 0, 0, 0), 'BASE', (8,)),
        ('TStreamerBase', 'TArrayS', 'Array of shorts',
         0, 0, 0, 0, (0, 56398612, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH1I": (0x627564f6, 3, (
        ('TStreamerBase', 'TH1', '1-Dim histogram base class',
         0, 0, 0, 0, (0, 473383108, 0, 0, 0), 'BASE', (8,)),
        ('TStreamerBase', 'TArrayI', 'Array of ints',
         0, 0, 0, 0, (0, -640323129, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH1F": (0xe2939644, 3, (
        ('TStreamerBase', 'TH1', '1-Dim histogram base class',
         0, 0, 0, 0, (0, 473383108, 0, 0, 0), 'BASE', (8,)),
        ('TStreamerBase', 'TArrayF', 'Array of floats',
         0, 0, 0, 0, (0, 1510733553, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH1D": (0xf9b1569f, 3, (
        ('TStreamerBase', 'TH1', '1-Dim histogram base class',
         0, 0, 0, 0, (0, 473383108, 0, 0, 0), 'BASE', (8,)),
        ('TStreamerBase', 'TArrayD', 'Array of doubles',
         0, 0, 0, 0, (0, 1899622196, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH2C": (0xbd0010fe, 4, (
        ('TStreamerBase', 'TH2', '2-Dim histogram base class',
         0, 0, 0, 0, (0, 25310335, 0, 0, 0), 'BASE', (5,)),
        ('TStreamerBase', 'TArrayC', 'Array of chars',
         0, 0, 0, 0, (0, -1366845130, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH2S": (0x1256ca1c, 4, (
        ('TStreamerBase', 'TH2', '2-Dim histogram base class',
         0, 0, 0, 0, (0, 25310335, 0, 0, 0), 'BASE', (5,)),
        ('TStreamerBase', 'TArrayS', 'Array of shorts',
         0, 0, 0, 0, (0, 56398612, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH2I": (0xe87e9147, 4, (
        ('TStreamerBase', 'TH2', '2-Dim histogram base class',
         0, 0, 0, 0, (0, 25310335, 0, 0, 0), 'BASE', (5,)),
        ('TStreamerBase', 'TArrayI', 'Array of ints',
         0, 0, 0, 0, (0, -640323129, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH2F": (0x689cc295, 4, (
        ('TStreamerBase', 'TH2', '2-Dim histogram base class',
         0, 0, 0, 0, (0, 25310335, 0, 0, 0), 'BASE', (5,)),
        ('TStreamerBase', 'TArrayF', 'Array of floats',
         0, 0, 0, 0, (0, 1510733553, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH2D": (0x7fba82f0, 4, (
        ('TStreamerBase', 'TH2', '2-Dim histogram base class',
         0, 0, 0, 0, (0, 25310335, 0, 0, 0), 'BASE', (5,)),
        ('TStreamerBase', 'TArrayD', 'Array of doubles',
         0, 0, 0, 0, (0, 1899622196, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH3C": (0xa1ff8d94, 4, (
        ('TStreamerBase', 'TH3', '3-Dim histogram base class',
         0, 0, 0, 0, (0, 1121076319, 0, 0, 0), 'BASE', (6,)),
        ('TStreamerBase', 'TArrayC', 'Array of chars',
         0, 0, 0, 0, (0, -1366845130, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH3S": (0xf75646b2, 4, (
        ('TStreamerBase', 'TH3', '3-Dim histogram base class',
         0, 0, 0, 0, (0, 1121076319, 0, 0, 0), 'BASE', (6,)),
        ('TStreamerBase', 'TArrayS', 'Array of shorts',
         0, 0, 0, 0, (0, 56398612, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH3I": (0xcd7e0ddd, 4, (
        ('TStreamerBase', 'TH3', '3-Dim histogram base class',
         0, 0, 0, 0, (0, 1121076319, 0, 0, 0), 'BASE', (6,)),
        ('TStreamerBase', 'TArrayI', 'Array of ints',
         0, 0, 0, 0, (0, -640323129, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH3F": (0x4d9c3f2b, 4, (
        ('TStreamerBase', 'TH3', '3-Dim histogram base class',
         0, 0, 0, 0, (0, 1121076319, 0, 0, 0), 'BASE', (6,)),
        ('TStreamerBase', 'TArrayF', 'Array of floats',
         0, 0, 0, 0, (0, 1510733553, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH3D": (0x64b9ff86, 4, (
        ('TStreamerBase', 'TH3', '3-Dim histogram base class',
         0, 0, 0, 0, (0, 1121076319, 0, 0, 0), 'BASE', (6,)),
        ('TStreamerBase', 'TArrayD', 'Array of doubles',
         0, 0, 0, 0, (0, 1899622196, 0, 0, 0), 'BASE', (1,)),
    )),
    "TH1": (0x1c3740c4, 8, (
        ('TStreamerBase', 'TNamed', 'The basis for a named object (name, title)',
         67, 0, 0, 0, (0, -541636036, 0, 0, 0), 'BASE', (1,)),
        ('TStreamerBase', 'TAttLine', 'Line attributes',
         0, 0, 0, 0, (0, -1811462839, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBase', 'TAttFill', 'Fill area attributes',
         0, 0, 0, 0, (0, -2545006, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBase', 'TAttMarker', 'Marker attributes',
         0, 0, 0, 0, (0, 689802220, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fNcells', 'number of bins(1D), cells (2D) +U/Overflows',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerObject', 'fXaxis', 'X axis descriptor',
         61, 216, 0, 0, (0, 0, 0, 0, 0), 'TAxis', ()),
        ('TStreamerObject', 'fYaxis', 'Y axis descriptor',
         61, 216, 0, 0, (0, 0, 0, 0, 0), 'TAxis', ()),
        ('TStreamerObject', 'fZaxis', 'Z axis descriptor',
         61, 216, 0, 0, (0, 0, 0, 0, 0), 'TAxis', ()),
        ('TStreamerBasicType', 'fBarOffset', '(1000*offset) for bar charts or legos',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
        ('TStreamerBasicType', 'fBarWidth', '(1000*width) for bar charts or legos',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
        ('TStreamerBasicType', 'fEntries', 'Number of entries',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumw', 'Total Sum of weights',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumw2', 'Total Sum of squares of weights',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwx', 'Total Sum of weight*X',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwx2', 'Total Sum of weight*X*X',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fMaximum', 'Maximum value for plotting',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fMinimum', 'Minimum value for plotting',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fNormFactor', 'Normalization factor',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerObjectAny', 'fContour', 'Array to display contour levels',
         62, 24, 0, 0, (0, 0, 0, 0, 0), 'TArrayD', ()),
        ('TStreamerObjectAny', 'fSumw2', 'Array of sum of squares of weights',
         62, 24, 0, 0, (0, 0, 0, 0, 0), 'TArrayD', ()),
        ('TStreamerString', 'fOption', 'histogram options',
         65, 24, 0, 0, (0, 0, 0, 0, 0), 'TString', ()),
        ('TStreamerObjectPointer', 'fFunctions', '->Pointer to list of functions (fits and user)',
         63, 8, 0, 0, (0, 0, 0, 0, 0), 'TList*', ()),
        ('TStreamerBasicType', 'fBufferSize', 'fBuffer size',
         6, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicPointer', 'fBuffer', '[fBufferSize] entry buffer',
         48, 8, 0, 0, (0, 0, 0, 0, 0), 'double*', (8, 'fBufferSize', 'TH1')),
        ('TStreamerBasicType', 'fBinStatErrOpt', 'option for bin statistical errors',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'TH1::EBinErrorOpt', ()),
        ('TStreamerBasicType', 'fStatOverflows',
         'per object flag to use under/overflows in statistics',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'TH1::EStatOverflows', ()),
    )),
    "TH2": (0x0182347f, 5, (
        ('TStreamerBase', 'TH1', '1-Dim histogram base class',
         0, 0, 0, 0, (0, 473383108, 0, 0, 0), 'BASE', (8,)),
        ('TStreamerBasicType', 'fScalefactor', 'Scale factor',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwy', 'Total Sum of weight*Y',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwy2', 'Total Sum of weight*Y*Y',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwxy', 'Total Sum of weight*X*Y',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
    )),
    "TH3": (0x42d2445f, 6, (
        ('TStreamerBase', 'TH1', '1-Dim histogram base class',
         0, 0, 0, 0, (0, 473383108, 0, 0, 0), 'BASE', (8,)),
        ('TStreamerBase', 'TAtt3D', '3D attributes',
         0, 0, 0, 0, (0, 30074, 0, 0, 0), 'BASE', (1,)),
        ('TStreamerBasicType', 'fTsumwy', 'Total Sum of weight*Y',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwy2', 'Total Sum of weight*Y*Y',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwxy', 'Total Sum of weight*X*Y',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwz', 'Total Sum of weight*Z',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwz2', 'Total Sum of weight*Z*Z',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwxz', 'Total Sum of weight*X*Z',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwyz', 'Total Sum of weight*Y*Z',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
    )),
    "TAtt3D": (0x0000757a, 1, (
    )),
    "TProfile": (0x4bedee54, 7, (
        ('TStreamerBase', 'TH1D', '1-Dim histograms (one double per channel)',
         0, 0, 0, 0, (0, -105818465, 0, 0, 0), 'BASE', (3,)),
        ('TStreamerObjectAny', 'fBinEntries', 'number of entries per bin',
         62, 24, 0, 0, (0, 0, 0, 0, 0), 'TArrayD', ()),
        ('TStreamerBasicType', 'fErrorMode', 'Option to compute errors',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'EErrorType', ()),
        ('TStreamerBasicType', 'fYmin', 'Lower limit in Y (if set)',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fYmax', 'Upper limit in Y (if set)',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwy', 'Total Sum of weight*Y',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwy2', 'Total Sum of weight*Y*Y',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerObjectAny', 'fBinSumw2', 'Array of sum of squares of weights per bin',
         62, 24, 0, 0, (0, 0, 0, 0, 0), 'TArrayD', ()),
    )),
    "TProfile2D": (0x36a142ac, 8, (
        ('TStreamerBase', 'TH2D', '2-Dim histograms (one double per channel)',
         0, 0, 0, 0, (0, 2142929648, 0, 0, 0), 'BASE', (4,)),
        ('TStreamerObjectAny', 'fBinEntries', 'number of entries per bin',
         62, 24, 0, 0, (0, 0, 0, 0, 0), 'TArrayD', ()),
        ('TStreamerBasicType', 'fErrorMode', 'Option to compute errors',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'EErrorType', ()),
        ('TStreamerBasicType', 'fZmin', 'Lower limit in Z (if set)',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fZmax', 'Upper limit in Z (if set)',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwz', 'Total Sum of weight*Z',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwz2', 'Total Sum of weight*Z*Z',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerObjectAny', 'fBinSumw2', 'Array of sum of squares of weights per bin',
         62, 24, 0, 0, (0, 0, 0, 0, 0), 'TArrayD', ()),
    )),
    "TProfile3D": (0xf60c6814, 8, (
        ('TStreamerBase', 'TH3D', '3-Dim histograms (one double per channel)',
         0, 0, 0, 0, (0, 1689911174, 0, 0, 0), 'BASE', (4,)),
        ('TStreamerObjectAny', 'fBinEntries', 'number of entries per bin',
         62, 24, 0, 0, (0, 0, 0, 0, 0), 'TArrayD', ()),
        ('TStreamerBasicType', 'fErrorMode', 'Option to compute errors',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'EErrorType', ()),
        ('TStreamerBasicType', 'fTmin', 'Lower limit in T (if set)',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTmax', 'Upper limit in T (if set)',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwt', 'Total Sum of weight*T',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTsumwt2', 'Total Sum of weight*T*T',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerObjectAny', 'fBinSumw2', 'Array of sum of squares of weights per bin',
         62, 24, 0, 0, (0, 0, 0, 0, 0), 'TArrayD', ()),
    )),
    "TEfficiency": (0x52931aeb, 2, (
        ('TStreamerBase', 'TNamed', 'The basis for a named object (name, title)',
         67, 0, 0, 0, (0, -541636036, 0, 0, 0), 'BASE', (1,)),
        ('TStreamerBase', 'TAttLine', 'Line attributes',
         0, 0, 0, 0, (0, -1811462839, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBase', 'TAttFill', 'Fill area attributes',
         0, 0, 0, 0, (0, -2545006, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBase', 'TAttMarker', 'Marker attributes',
         0, 0, 0, 0, (0, 689802220, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fBeta_alpha',
         'global parameter for prior beta distribution (default = 1)',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fBeta_beta',
         'global parameter for prior beta distribution (default = 1)',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerSTL', 'fBeta_bin_params',
         'parameter for prior beta distribution different bin by bin',
         500, 24, 0, 0, (0, 0, 0, 0, 0), 'vector<pair<double,double> >', (1, 61)),
        ('TStreamerBasicType', 'fConfLevel', 'confidence level (default = 0.683, 1 sigma)',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerObjectPointer', 'fFunctions', '->pointer to list of functions',
         63, 8, 0, 0, (0, 0, 0, 0, 0), 'TList*', ()),
        ('TStreamerObjectPointer', 'fPassedHistogram',
         'histogram for events which passed certain criteria',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'TH1*', ()),
        ('TStreamerBasicType', 'fStatisticOption',
         'defines how the confidence intervals are determined',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'TEfficiency::EStatOption', ()),
        ('TStreamerObjectPointer', 'fTotalHistogram', 'histogram for total number of events',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'TH1*', ()),
        ('TStreamerBasicType', 'fWeight', 'weight for all events (default = 1)',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
    )),
    "TF1": (0x7223ffd8, 12, (
        ('TStreamerBase', 'TNamed', 'The basis for a named object (name, title)',
         67, 0, 0, 0, (0, -541636036, 0, 0, 0), 'BASE', (1,)),
        ('TStreamerBase', 'TAttLine', 'Line attributes',
         0, 0, 0, 0, (0, -1811462839, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBase', 'TAttFill', 'Fill area attributes',
         0, 0, 0, 0, (0, -2545006, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBase', 'TAttMarker', 'Marker attributes',
         0, 0, 0, 0, (0, 689802220, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fXmin', 'Lower bounds for the range',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fXmax', 'Upper bounds for the range',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fNpar', 'Number of parameters',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fNdim', 'Function dimension',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fNpx', 'Number of points used for the graphical representation',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fType', '',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'TF1::EFType', ()),
        ('TStreamerBasicType', 'fNpfits', 'Number of points used in the fit',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fNDF', 'Number of degrees of freedom in the fit',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fChisquare', 'Function fit chisquare',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fMinimum', 'Minimum value for plotting',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fMaximum', 'Maximum value for plotting',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerSTL', 'fParErrors', 'Array of errors of the fNpar parameters',
         500, 24, 0, 0, (0, 0, 0, 0, 0), 'vector<double>', (1, 8)),
        ('TStreamerSTL', 'fParMin', 'Array of lower limits of the fNpar parameters',
         500, 24, 0, 0, (0, 0, 0, 0, 0), 'vector<double>', (1, 8)),
        ('TStreamerSTL', 'fParMax', 'Array of upper limits of the fNpar parameters',
         500, 24, 0, 0, (0, 0, 0, 0, 0), 'vector<double>', (1, 8)),
        ('TStreamerSTL', 'fSave', 'Array of fNsave function values',
         500, 24, 0, 0, (0, 0, 0, 0, 0), 'vector<double>', (1, 8)),
        ('TStreamerBasicType', 'fNormalized', 'Normalization option (false by default)',
         18, 1, 0, 0, (0, 0, 0, 0, 0), 'bool', ()),
        ('TStreamerBasicType', 'fNormIntegral', 'Integral of the function before being normalized',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerObjectPointer', 'fFormula',
         'Pointer to TFormula in case when user define formula',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'TFormula', ()),
        ('TStreamerObjectAnyPointer', 'fParams',
         'Pointer to Function parameters object (exists only for not-formula functions)',
         69, 8, 0, 0, (0, 0, 0, 0, 0), 'TF1Parameters', ()),
        ('TStreamerObjectPointer', 'fComposition', 'Pointer to composition (NSUM or CONV)',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'TF1AbsComposition', ()),
    )),
    "TFormula": (0x3d29ef01, 13, (
        ('TStreamerBase', 'TNamed', 'The basis for a named object (name, title)',
         67, 0, 0, 0, (0, -541636036, 0, 0, 0), 'BASE', (1,)),
        ('TStreamerSTL', 'fClingParameters', 'parameter values',
         500, 24, 0, 0, (0, 0, 0, 0, 0), 'vector<double>', (1, 8)),
        ('TStreamerBasicType', 'fAllParametersSetted',
         'flag to control if all parameters are setted',
         18, 1, 0, 0, (0, 0, 0, 0, 0), 'bool', ()),
        ('TStreamerSTL', 'fParams', '|| list of  parameter names',
         500, 48, 0, 0, (0, 0, 0, 0, 0), 'map<TString,int,TFormulaParamOrder>', (4, 61)),
        ('TStreamerString', 'fFormula', 'string representing the formula expression',
         65, 24, 0, 0, (0, 0, 0, 0, 0), 'TString', ()),
        ('TStreamerBasicType', 'fNdim', 'Dimension - needed for lambda expressions',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerSTL', 'fLinearParts', 'vector of linear functions',
         500, 24, 0, 0, (0, 0, 0, 0, 0), 'vector<TObject*>', (1, 63)),
        ('TStreamerBasicType', 'fVectorized',
         'whether we should use vectorized or regular variables',
         18, 1, 0, 0, (0, 0, 0, 0, 0), 'bool', ()),
    )),
    "TF1Parameters": (0xd703028e, 1, (
        ('TStreamerSTL', 'fParameters', 'parameter values',
         500, 24, 0, 0, (0, 0, 0, 0, 0), 'vector<double>', (1, 8)),
        ('TStreamerSTL', 'fParNames', 'parameter names',
         500, 24, 0, 0, (0, 0, 0, 0, 0), 'vector<string>', (1, 61)),
    )),
    "TF1AbsComposition": (0xa71d6529, 1, (
        ('TStreamerBase', 'TObject', 'Basic ROOT object',
         66, 0, 0, 0, (0, -1877229523, 0, 0, 0), 'BASE', (1,)),
    )),
    "TGraph": (0x05f7f465, 4, (
        ('TStreamerBase', 'TNamed', 'The basis for a named object (name, title)',
         67, 0, 0, 0, (0, -541636036, 0, 0, 0), 'BASE', (1,)),
        ('TStreamerBase', 'TAttLine', 'Line attributes',
         0, 0, 0, 0, (0, -1811462839, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBase', 'TAttFill', 'Fill area attributes',
         0, 0, 0, 0, (0, -2545006, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBase', 'TAttMarker', 'Marker attributes',
         0, 0, 0, 0, (0, 689802220, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fNpoints', 'Number of points <= fMaxSize',
         6, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicPointer', 'fX', '[fNpoints] array of X points',
         48, 8, 0, 0, (0, 0, 0, 0, 0), 'double*', (4, 'fNpoints', 'TGraph')),
        ('TStreamerBasicPointer', 'fY', '[fNpoints] array of Y points',
         48, 8, 0, 0, (0, 0, 0, 0, 0), 'double*', (4, 'fNpoints', 'TGraph')),
        ('TStreamerObjectPointer', 'fFunctions', 'Pointer to list of functions (fits and user)',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'TList*', ()),
        ('TStreamerObjectPointer', 'fHistogram', 'Pointer to histogram used for drawing axis',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'TH1F*', ()),
        ('TStreamerBasicType', 'fMinimum', 'Minimum value for plotting along y',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fMaximum', 'Maximum value for plotting along y',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
    )),
    "TGraphErrors": (0x2a7ce30f, 3, (
        ('TStreamerBase', 'TGraph', 'Graph graphics class',
         0, 0, 0, 0, (0, 100136037, 0, 0, 0), 'BASE', (4,)),
        ('TStreamerBasicPointer', 'fEX', '[fNpoints] array of X errors',
         48, 8, 0, 0, (0, 0, 0, 0, 0), 'double*', (4, 'fNpoints', 'TGraph')),
        ('TStreamerBasicPointer', 'fEY', '[fNpoints] array of Y errors',
         48, 8, 0, 0, (0, 0, 0, 0, 0), 'double*', (4, 'fNpoints', 'TGraph')),
    )),
    "TGraphAsymmErrors": (0xcc46af3b, 3, (
        ('TStreamerBase', 'TGraph', 'Graph graphics class',
         0, 0, 0, 0, (0, 100136037, 0, 0, 0), 'BASE', (4,)),
        ('TStreamerBasicPointer', 'fEXlow', '[fNpoints] array of X low errors',
         48, 8, 0, 0, (0, 0, 0, 0, 0), 'double*', (4, 'fNpoints', 'TGraph')),
        ('TStreamerBasicPointer', 'fEXhigh', '[fNpoints] array of X high errors',
         48, 8, 0, 0, (0, 0, 0, 0, 0), 'double*', (4, 'fNpoints', 'TGraph')),
        ('TStreamerBasicPointer', 'fEYlow', '[fNpoints] array of Y low errors',
         48, 8, 0, 0, (0, 0, 0, 0, 0), 'double*', (4, 'fNpoints', 'TGraph')),
        ('TStreamerBasicPointer', 'fEYhigh', '[fNpoints] array of Y high errors',
         48, 8, 0, 0, (0, 0, 0, 0, 0), 'double*', (4, 'fNpoints', 'TGraph')),
    )),
    "TTree": (0x58a396eb, 19, (
        ('TStreamerBase', 'TNamed', 'The basis for a named object (name, title)',
         67, 0, 0, 0, (0, -541636036, 0, 0, 0), 'BASE', (1,)),
        ('TStreamerBase', 'TAttLine', 'Line attributes',
         0, 0, 0, 0, (0, -1811462839, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBase', 'TAttFill', 'Fill area attributes',
         0, 0, 0, 0, (0, -2545006, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBase', 'TAttMarker', 'Marker attributes',
         0, 0, 0, 0, (0, 689802220, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fEntries', 'Number of entries',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fTotBytes',
         'Total number of bytes in all branches before compression',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fZipBytes',
         'Total number of bytes in all branches after compression',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fSavedBytes', 'Number of autosaved bytes',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fFlushedBytes', 'Number of auto-flushed bytes',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fWeight', 'Tree weight (see TTree::SetWeight)',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fTimerInterval', 'Timer interval in milliseconds',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fScanField', 'Number of runs before prompting in Scan',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fUpdate', 'Update frequency for EntryLoop',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fDefaultEntryOffsetLen',
         'Initial Length of fEntryOffset table in the basket buffers',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fNClusterRange',
         "Number of Cluster range in addition to the one defined by 'AutoFlush'",
         6, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fMaxEntries',
         'Maximum number of entries in case of circular buffers',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fMaxEntryLoop', 'Maximum number of entries to process',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fMaxVirtualSize', 'Maximum total size of buffers kept in memory',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fAutoSave',
         'Autosave tree when fAutoSave entries written or -fAutoSave (compressed) bytes produced',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fAutoFlush',
         'Auto-flush tree when fAutoFlush entries written or -fAutoFlush (compressed) by'
         'tes produced',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fEstimate', 'Number of entries to estimate histogram limits',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicPointer', 'fClusterRangeEnd',
         '[fNClusterRange] Last entry of a cluster range.',
         56, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t*', (19, 'fNClusterRange', 'TTree')),
        ('TStreamerBasicPointer', 'fClusterSize',
         '[fNClusterRange] Number of entries in each cluster for a given range.',
         56, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t*', (19, 'fNClusterRange', 'TTree')),
        ('TStreamerObject', 'fBranches', 'List of Branches',
         61, 64, 0, 0, (0, 0, 0, 0, 0), 'TObjArray', ()),
        ('TStreamerObject', 'fLeaves', 'Direct pointers to individual branch leaves',
         61, 64, 0, 0, (0, 0, 0, 0, 0), 'TObjArray', ()),
        ('TStreamerObjectPointer', 'fAliases',
         'List of aliases for expressions based on the tree branches.',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'TList*', ()),
        ('TStreamerObjectAny', 'fIndexValues', 'Sorted index values',
         62, 24, 0, 0, (0, 0, 0, 0, 0), 'TArrayD', ()),
        ('TStreamerObjectAny', 'fIndex', 'Index of sorted values',
         62, 24, 0, 0, (0, 0, 0, 0, 0), 'TArrayI', ()),
        ('TStreamerObjectPointer', 'fTreeIndex', 'Pointer to the tree Index (if any)',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'TVirtualIndex*', ()),
        ('TStreamerObjectPointer', 'fFriends', 'pointer to list of friend elements',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'TList*', ()),
        ('TStreamerObjectPointer', 'fUserInfo',
         'pointer to a list of user objects associated to this Tree',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'TList*', ()),
        ('TStreamerObjectPointer', 'fBranchRef', 'Branch supporting the TRefTable (if any)',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'TBranchRef*', ()),
    )),
    "TBranch": (0x59108cb8, 12, (
        ('TStreamerBase', 'TNamed', 'The basis for a named object (name, title)',
         67, 0, 0, 0, (0, -541636036, 0, 0, 0), 'BASE', (1,)),
        ('TStreamerBase', 'TAttFill', 'Fill area attributes',
         0, 0, 0, 0, (0, -2545006, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fCompress', 'Compression level and algorithm',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fBasketSize', 'Initial Size of  Basket Buffer',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fEntryOffsetLen',
         'Initial Length of fEntryOffset table in the basket buffers',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fWriteBasket', 'Last basket number written',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fEntryNumber',
         'Current entry number (last one filled in this branch)',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fOffset', 'Offset of this branch',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fMaxBaskets', 'Maximum number of Baskets so far',
         6, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fSplitLevel', 'Branch split level',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fEntries', 'Number of entries',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fFirstEntry', 'Number of the first entry in this branch',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fTotBytes',
         'Total number of bytes in all leaves before compression',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fZipBytes', 'Total number of bytes in all leaves after compression',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerObject', 'fBranches', '-> List of Branches of this branch',
         61, 64, 0, 0, (0, 0, 0, 0, 0), 'TObjArray', ()),
        ('TStreamerObject', 'fLeaves', '-> List of leaves of this branch',
         61, 64, 0, 0, (0, 0, 0, 0, 0), 'TObjArray', ()),
        ('TStreamerObject', 'fBaskets', '-> List of baskets of this branch',
         61, 64, 0, 0, (0, 0, 0, 0, 0), 'TObjArray', ()),
        ('TStreamerBasicPointer', 'fBasketBytes', '[fMaxBaskets] Length of baskets on file',
         43, 4, 0, 0, (0, 0, 0, 0, 0), 'int*', (12, 'fMaxBaskets', 'TBranch')),
        ('TStreamerBasicPointer', 'fBasketEntry',
         '[fMaxBaskets] Table of first entry in each basket',
         56, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t*', (12, 'fMaxBaskets', 'TBranch')),
        ('TStreamerBasicPointer', 'fBasketSeek', '[fMaxBaskets] Addresses of baskets on file',
         56, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t*', (12, 'fMaxBaskets', 'TBranch')),
        ('TStreamerString', 'fFileName',
         'Name of file where buffers are stored ("" if in same file as Tree header)',
         65, 24, 0, 0, (0, 0, 0, 0, 0), 'TString', ()),
    )),
    "TLeaf": (0x6d1e8152, 2, (
        ('TStreamerBase', 'TNamed', 'The basis for a named object (name, title)',
         67, 0, 0, 0, (0, -541636036, 0, 0, 0), 'BASE', (1,)),
        ('TStreamerBasicType', 'fLen', 'Number of fixed length elements',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fLenType', 'Number of bytes for this data type',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fOffset', 'Offset in ClonesArray object (if one)',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fIsRange', '(=kTRUE if leaf has a range, kFALSE otherwise)',
         18, 1, 0, 0, (0, 0, 0, 0, 0), 'bool', ()),
        ('TStreamerBasicType', 'fIsUnsigned', '(=kTRUE if unsigned, kFALSE otherwise)',
         18, 1, 0, 0, (0, 0, 0, 0, 0), 'bool', ()),
        ('TStreamerObjectPointer', 'fLeafCount',
         'Pointer to Leaf count if variable length (we do not own the counter)',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'TLeaf*', ()),
    )),
    "TLeafO": (0x02ae48d3, 1, (
        ('TStreamerBase', 'TLeaf', 'Leaf: description of a Branch data type',
         0, 0, 0, 0, (0, 1830715730, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fMinimum', 'Minimum value if leaf range is specified',
         18, 1, 0, 0, (0, 0, 0, 0, 0), 'bool', ()),
        ('TStreamerBasicType', 'fMaximum', 'Maximum value if leaf range is specified',
         18, 1, 0, 0, (0, 0, 0, 0, 0), 'bool', ()),
    )),
    "TLeafB": (0x0f1e4b5e, 1, (
        ('TStreamerBase', 'TLeaf', 'Leaf: description of a Branch data type',
         0, 0, 0, 0, (0, 1830715730, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fMinimum', 'Minimum value if leaf range is specified',
         1, 1, 0, 0, (0, 0, 0, 0, 0), 'char', ()),
        ('TStreamerBasicType', 'fMaximum', 'Maximum value if leaf range is specified',
         1, 1, 0, 0, (0, 0, 0, 0, 0), 'char', ()),
    )),
    "TLeafS": (0x150ceecf, 1, (
        ('TStreamerBase', 'TLeaf', 'Leaf: description of a Branch data type',
         0, 0, 0, 0, (0, 1830715730, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fMinimum', 'Minimum value if leaf range is specified',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
        ('TStreamerBasicType', 'fMaximum', 'Maximum value if leaf range is specified',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
    )),
    "TLeafI": (0x7e6aae19, 1, (
        ('TStreamerBase', 'TLeaf', 'Leaf: description of a Branch data type',
         0, 0, 0, 0, (0, 1830715730, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fMinimum', 'Minimum value if leaf range is specified',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fMaximum', 'Maximum value if leaf range is specified',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
    )),
    "TLeafL": (0xde320862, 1, (
        ('TStreamerBase', 'TLeaf', 'Leaf: description of a Branch data type',
         0, 0, 0, 0, (0, 1830715730, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fMinimum', 'Minimum value if leaf range is specified',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
        ('TStreamerBasicType', 'fMaximum', 'Maximum value if leaf range is specified',
         16, 8, 0, 0, (0, 0, 0, 0, 0), 'Long64_t', ()),
    )),
    "TLeafF": (0x3add9d72, 1, (
        ('TStreamerBase', 'TLeaf', 'Leaf: description of a Branch data type',
         0, 0, 0, 0, (0, 1830715730, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fMinimum', 'Minimum value if leaf range is specified',
         5, 4, 0, 0, (0, 0, 0, 0, 0), 'float', ()),
        ('TStreamerBasicType', 'fMaximum', 'Maximum value if leaf range is specified',
         5, 4, 0, 0, (0, 0, 0, 0, 0), 'float', ()),
    )),
    "TLeafD": (0x118e8776, 1, (
        ('TStreamerBase', 'TLeaf', 'Leaf: description of a Branch data type',
         0, 0, 0, 0, (0, 1830715730, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fMinimum', 'Minimum value if leaf range is specified',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fMaximum', 'Maximum value if leaf range is specified',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
    )),
    "TLeafC": (0xfbe3b2f3, 1, (
        ('TStreamerBase', 'TLeaf', 'Leaf: description of a Branch data type',
         0, 0, 0, 0, (0, 1830715730, 0, 0, 0), 'BASE', (2,)),
        ('TStreamerBasicType', 'fMinimum', 'Minimum value if leaf range is specified',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fMaximum', 'Maximum value if leaf range is specified',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
    )),
    "TObjArray": (0xa99e6552, 3, (
        ('TStreamerBase', 'TSeqCollection', 'Sequenceable collection ABC',
         0, 0, 0, 0, (0, -60015674, 0, 0, 0), 'BASE', (0,)),
        ('TStreamerBasicType', 'fLowerBound', 'Lower bound of the array',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fLast', 'Last element in array containing an object',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
    )),
    "TNamed": (0xdfb74a3c, 1, (
        ('TStreamerBase', 'TObject', 'Basic ROOT object',
         66, 0, 0, 0, (0, -1877229523, 0, 0, 0), 'BASE', (1,)),
        ('TStreamerString', 'fName', 'object identifier',
         65, 24, 0, 0, (0, 0, 0, 0, 0), 'TString', ()),
        ('TStreamerString', 'fTitle', 'object title',
         65, 24, 0, 0, (0, 0, 0, 0, 0), 'TString', ()),
    )),
    "TObject": (0x901bc02d, 1, (
        ('TStreamerBasicType', 'fUniqueID', 'object unique identifier',
         13, 4, 0, 0, (0, 0, 0, 0, 0), 'unsigned int', ()),
        ('TStreamerBasicType', 'fBits', 'bit field status word',
         15, 4, 0, 0, (0, 0, 0, 0, 0), 'unsigned int', ()),
    )),
    "TAttLine": (0x94074549, 2, (
        ('TStreamerBasicType', 'fLineColor', 'Line color',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
        ('TStreamerBasicType', 'fLineStyle', 'Line style',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
        ('TStreamerBasicType', 'fLineWidth', 'Line width',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
    )),
    "TAttFill": (0xffd92a92, 2, (
        ('TStreamerBasicType', 'fFillColor', 'Fill area color',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
        ('TStreamerBasicType', 'fFillStyle', 'Fill area style',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
    )),
    "TAttMarker": (0x291d8bec, 2, (
        ('TStreamerBasicType', 'fMarkerColor', 'Marker color',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
        ('TStreamerBasicType', 'fMarkerStyle', 'Marker style',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
        ('TStreamerBasicType', 'fMarkerSize', 'Marker size',
         5, 4, 0, 0, (0, 0, 0, 0, 0), 'float', ()),
    )),
    "TAxis": (0x5a496e70, 10, (
        ('TStreamerBase', 'TNamed', 'The basis for a named object (name, title)',
         67, 0, 0, 0, (0, -541636036, 0, 0, 0), 'BASE', (1,)),
        ('TStreamerBase', 'TAttAxis', 'Axis attributes',
         0, 0, 0, 0, (0, 1550843710, 0, 0, 0), 'BASE', (4,)),
        ('TStreamerBasicType', 'fNbins', 'Number of bins',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fXmin', 'low edge of first bin',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerBasicType', 'fXmax', 'upper edge of last bin',
         8, 8, 0, 0, (0, 0, 0, 0, 0), 'double', ()),
        ('TStreamerObjectAny', 'fXbins', 'Bin edges array in X',
         62, 24, 0, 0, (0, 0, 0, 0, 0), 'TArrayD', ()),
        ('TStreamerBasicType', 'fFirst', 'first bin to display',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fLast', 'last bin to display',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fBits2', 'second bit status word',
         12, 2, 0, 0, (0, 0, 0, 0, 0), 'unsigned short', ()),
        ('TStreamerBasicType', 'fTimeDisplay', 'on/off displaying time values instead of numerics',
         18, 1, 0, 0, (0, 0, 0, 0, 0), 'bool', ()),
        ('TStreamerString', 'fTimeFormat', 'Date&time format, ex: 09/12/99 12:34:00',
         65, 24, 0, 0, (0, 0, 0, 0, 0), 'TString', ()),
        ('TStreamerObjectPointer', 'fLabels', 'List of labels',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'THashList*', ()),
        ('TStreamerObjectPointer', 'fModLabs', 'List of modified labels',
         64, 8, 0, 0, (0, 0, 0, 0, 0), 'TList*', ()),
    )),
    "TAttAxis": (0x5c6fff3e, 4, (
        ('TStreamerBasicType', 'fNdivisions', 'Number of divisions(10000*n3 + 100*n2 + n1)',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
        ('TStreamerBasicType', 'fAxisColor', 'Color of the line axis',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
        ('TStreamerBasicType', 'fLabelColor', 'Color of labels',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
        ('TStreamerBasicType', 'fLabelFont', 'Font for labels',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
        ('TStreamerBasicType', 'fLabelOffset', 'Offset of labels',
         5, 4, 0, 0, (0, 0, 0, 0, 0), 'float', ()),
        ('TStreamerBasicType', 'fLabelSize', 'Size of labels',
         5, 4, 0, 0, (0, 0, 0, 0, 0), 'float', ()),
        ('TStreamerBasicType', 'fTickLength', 'Length of tick marks',
         5, 4, 0, 0, (0, 0, 0, 0, 0), 'float', ()),
        ('TStreamerBasicType', 'fTitleOffset', 'Offset of axis title',
         5, 4, 0, 0, (0, 0, 0, 0, 0), 'float', ()),
        ('TStreamerBasicType', 'fTitleSize', 'Size of axis title',
         5, 4, 0, 0, (0, 0, 0, 0, 0), 'float', ()),
        ('TStreamerBasicType', 'fTitleColor', 'Color of axis title',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
        ('TStreamerBasicType', 'fTitleFont', 'Font for axis title',
         2, 2, 0, 0, (0, 0, 0, 0, 0), 'short', ()),
    )),
    "THashList": (0xcc7e49c1, 0, (
        ('TStreamerBase', 'TList', 'Doubly linked list',
         0, 0, 0, 0, (0, 1774568379, 0, 0, 0), 'BASE', (5,)),
    )),
    "TList": (0x69c5c3bb, 5, (
        ('TStreamerBase', 'TSeqCollection', 'Sequenceable collection ABC',
         0, 0, 0, 0, (0, -60015674, 0, 0, 0), 'BASE', (0,)),
    )),
    "TSeqCollection": (0xfc6c3bc6, 0, (
        ('TStreamerBase', 'TCollection', 'Collection abstract base class',
         0, 0, 0, 0, (0, 1474546588, 0, 0, 0), 'BASE', (3,)),
    )),
    "TCollection": (0x57e3cb9c, 3, (
        ('TStreamerBase', 'TObject', 'Basic ROOT object',
         66, 0, 0, 0, (0, -1877229523, 0, 0, 0), 'BASE', (1,)),
        ('TStreamerString', 'fName', 'name of the collection',
         65, 24, 0, 0, (0, 0, 0, 0, 0), 'TString', ()),
        ('TStreamerBasicType', 'fSize', 'number of elements in collection',
         3, 4, 0, 0, (0, 0, 0, 0, 0), 'int', ()),
    )),
    "TString": (0x00017419, 2, (
    )),
}
